In [489]:
import numpy as np
import random

In [490]:
x1 = 2*np.random.rand(100,1)
x2 = 2*np.random.rand(100,1)
y = 3*x1 + 4*x2 + np.random.rand(100,1)+2


In [491]:
from numpy.linalg import inv
x1 = x1.reshape((100, 1))
x2 = x2.reshape((100, 1))
x3 = np.ones((100, 1))
x = np.hstack((x1, x2, x3))
y = y.reshape((100,))
theta = inv(x.T.dot(x)).dot(x.T).dot(y)
print theta

[ 2.92728374  4.02283263  2.557499  ]


In [492]:
def gradD(x,y,theta,aerfa,cnt,j):
    xT = x.transpose()
    #a = []
    #b = []
    targetCost = 100000
    tup1 =(theta,targetCost)
    for i in range(0,j):
        tar = np.dot(x,theta)
        lose = tar-y
        cost = np.sum(lose**2)/(2*m)
        if cost<targetCost:
            targetCost = cost
            tup1 = (theta,targetCost,aerfa)
        #a.append(cost)
        #b.append(i)
        #print(cost)
        grad = np.dot(xT,lose)/cnt
        theta = theta-aerfa*grad
     
    return theta,tup1#,a,b

In [493]:
m,n = np.shape(x)
j = 10000
aerfa = 0.005
theta = np.ones(n)
theta = gradD(x,y,theta,aerfa,m,j)
print(theta)

(array([ 2.92614754,  4.02200366,  2.55975867]), (array([ 2.92614696,  4.02200324,  2.55975983]), 0.040496380691493757, 0.005))


In [494]:
#import matplotlib.pyplot as plt
m,n = np.shape(x)
j = 10000
while aerfa < 0.05:
    aerfa += 0.001
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    p = (np.var(y))**(1/2)
    print( theta)
    #z = np.random.uniform(20,20,20)
    #s = theta[2][1]
    #b = theta[2][2]
    #plt.scatter(s,b,s=z,c='r',alpha = 0.4,lw = 0)
    #tup1 = gradD(x,y,theta,aerfa,m,j)
    
#helper(a,b)
    #plt.figure()
#plt.scatter(a,b)
#plt.show()

(array([ 2.92687515,  4.02253452,  2.5583116 ]), (array([ 2.9268749 ,  4.02253434,  2.5583121 ]), 0.040496065136987863, 0.006))
(array([ 2.92713682,  4.02272544,  2.55779118]), (array([ 2.92713672,  4.02272536,  2.55779139]), 0.040496024320177702, 0.007))
(array([ 2.92723092,  4.02279409,  2.55760405]), (array([ 2.92723088,  4.02279406,  2.55760413]), 0.040496019041649053, 0.008))
(array([ 2.92726475,  4.02281877,  2.55753676]), (array([ 2.92726473,  4.02281876,  2.5575368 ]), 0.040496018359159808, 0.009000000000000001))
(array([ 2.92727692,  4.02282765,  2.55751257]), (array([ 2.92727691,  4.02282764,  2.55751258]), 0.04049601827093556, 0.010000000000000002))
(array([ 2.92728129,  4.02283084,  2.55750387]), (array([ 2.92728128,  4.02283083,  2.55750388]), 0.040496018259533341, 0.011000000000000003))
(array([ 2.92728286,  4.02283198,  2.55750075]), (array([ 2.92728286,  4.02283198,  2.55750075]), 0.040496018258060061, 0.012000000000000004))
(array([ 2.92728342,  4.02283239,  2.55749963

In [495]:
m,n = np.shape(x)
j = 10000
aerfa = 0
while aerfa < 0.01:
    aerfa += 0.001
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    print(theta)
   # tup1 = gradD(x,y,theta,aerfa,m,j)
   # print(tup1)

(array([ 2.86992612,  3.96169684,  2.69350174]), (array([ 2.86992337,  3.96168715,  2.69351594]), 0.041837336475294994, 0.001))
(array([ 2.90306201,  4.00480281,  2.6060782 ]), (array([ 2.90305717,  4.004799  ,  2.60608814]), 0.040663309806134133, 0.002))
(array([ 2.9185041 ,  4.01642044,  2.57496754]), (array([ 2.91850141,  4.01641847,  2.5749729 ]), 0.040517668052709038, 0.003))
(array([ 2.92412461,  4.02052762,  2.56378205]), (array([ 2.92412332,  4.02052668,  2.56378462]), 0.040498819731226883, 0.004))
(array([ 2.92614754,  4.02200366,  2.55975867]), (array([ 2.92614696,  4.02200324,  2.55975983]), 0.040496380691493757, 0.005))
(array([ 2.92687515,  4.02253452,  2.5583116 ]), (array([ 2.9268749 ,  4.02253434,  2.5583121 ]), 0.040496065136987863, 0.006))
(array([ 2.92713682,  4.02272544,  2.55779118]), (array([ 2.92713672,  4.02272536,  2.55779139]), 0.040496024320177702, 0.007))
(array([ 2.92723092,  4.02279409,  2.55760405]), (array([ 2.92723088,  4.02279406,  2.55760413]), 0.0404

In [496]:
m,n = np.shape(x)
j = 10000
aerfa = 0.01
while aerfa < 0.02:
    aerfa += 0.0005
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    print(theta)

(array([ 2.92727965,  4.02282964,  2.55750713]), (array([ 2.92727964,  4.02282964,  2.55750714]), 0.040496018262548394, 0.0105))
(array([ 2.92728129,  4.02283084,  2.55750387]), (array([ 2.92728128,  4.02283083,  2.55750388]), 0.040496018259533341, 0.011000000000000001))
(array([ 2.92728227,  4.02283155,  2.55750192]), (array([ 2.92728227,  4.02283155,  2.55750192]), 0.040496018258449569, 0.011500000000000002))
(array([ 2.92728286,  4.02283198,  2.55750075]), (array([ 2.92728286,  4.02283198,  2.55750075]), 0.040496018258060061, 0.012000000000000002))
(array([ 2.92728321,  4.02283224,  2.55750005]), (array([ 2.92728321,  4.02283224,  2.55750005]), 0.040496018257920013, 0.012500000000000002))
(array([ 2.92728342,  4.02283239,  2.55749963]), (array([ 2.92728342,  4.02283239,  2.55749963]), 0.040496018257869665, 0.013000000000000003))
(array([ 2.92728355,  4.02283249,  2.55749937]), (array([ 2.92728355,  4.02283249,  2.55749937]), 0.040496018257851575, 0.013500000000000003))
(array([ 2.92

In [497]:
m,n = np.shape(x)
j = 10000
aerfa = 0.02
while aerfa < 0.03:
    aerfa += 0.0005
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    print(theta)

(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841396, 0.0205))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841389, 0.021))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841368, 0.021500000000000002))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841389, 0.022000000000000002))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841382, 0.022500000000000003))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841382, 0.023000000000000003))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841389, 0.023500000000000004))
(array([ 2.92728374,  4.0228

In [498]:
m,n = np.shape(x)
j = 10000
aerfa = 0.03
while aerfa < 0.04:
    aerfa += 0.0005
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    print(theta)

(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841368, 0.0305))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841389, 0.031))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841382, 0.0315))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841368, 0.032))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841389, 0.0325))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841389, 0.033))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841382, 0.0335))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.

In [499]:
m,n = np.shape(x)
j = 10000
aerfa = 0.04
while aerfa < 0.05:
    aerfa += 0.0005
    theta = np.ones(n)
    theta = gradD(x,y,theta,aerfa,m,j)
    print(theta)

(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841382, 0.0405))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841389, 0.041))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.55749901]), 0.040496018257841382, 0.0415))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841389, 0.042))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841389, 0.0425))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283262,  2.557499  ]), 0.040496018257841389, 0.043000000000000003))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  4.02283263,  2.557499  ]), 0.040496018257841382, 0.043500000000000004))
(array([ 2.92728374,  4.02283263,  2.557499  ]), (array([ 2.92728374,  